const endPoints = {
  USERS: '/users',
  AUTH_REGISTER: '/register',
  AUTH_LOGIN: '/login',
  AUTH_LOGOUT: '/api/Auth/Logout',
  AUTH_ME: '/manage/info',
  USER_ACTIVE: '/api/User/GetAllActiveUsers',
  PROFILE_ME: '/api/Profile/GetMyProfile',
  PROFILE_UPDATE_ME: '/api/Profile/UpdateMyProfile',
  PROFILE_CHANGE_PASSWORD: '/api/Profile/ChangePassword',
  POST_FEED: '/api/Post/GetFeed',
  POST_MY_POSTS: '/api/Post/GetMyPosts',
  POST_CREATE: '/api/Post/Create',
  POST_UPDATE: '/api/Post/Update',
  POST_DELETE: '/api/Post/Delete',
  POST_TOGGLE_LIKE: '/api/Post/ToggleLike',
  REPORT_CREATE_POST: '/api/Report/CreatePostReport',
  FRIEND_FOLLOW: '/api/Friend/Follow',
  FRIEND_UNFOLLOW: '/api/Friend/Unfollow',
  FRIEND_GET_FOLLOWING: '/api/Friend/GetFollowing',
  FRIEND_SEND_REQUEST: '/api/Friend/SendRequest',
  FRIEND_ACCEPT_REQUEST: '/api/Friend/AcceptRequest',
  FRIEND_REJECT_REQUEST: '/api/Friend/RejectRequest',
  FRIEND_GET_PENDING_RECEIVED: '/api/Friend/GetPendingReceivedRequests',
  FRIEND_GET_PENDING_SENT: '/api/Friend/GetPendingSentRequests',
  FRIEND_GET_FRIENDS: '/api/Friend/GetFriends',
  FRIEND_REMOVE: '/api/Friend/RemoveFriend',
  NOTIFICATION_LIST: '/api/Notification',
  NOTIFICATION_UNREAD_COUNT: '/api/Notification/UnreadCount',
  NOTIFICATION_MARK_AS_READ: '/api/Notification/MarkAsRead',
  NOTIFICATION_MARK_ALL_AS_READ: '/api/Notification/MarkAllAsRead',
}

export default endPoints
